Sources/WalletConnect/JSONRPC/JSONRPC.swift, Sources/WalletConnect/Types/ClientSynchJSONRPC/ClientSynchJSONRPC.swift
close #27 
@MisterVants I was supposed to continue on this branch with responses deserialisation but as you took it over, let's just merge this small issue.
=> #27 Generate JSONRPC request id suffixed with random digits

Sources/WalletConnect/Relay/JSONRPCResponseType.swift, Sources/WalletConnect/Relay/Relay.swift, Sources/WalletConnect/Relay/RelaySubscriber.swift, Tests/WalletConnectTests/Mocks/MockedRelaySubscriber.swift, Tests/WalletConnectTests/RelayTests.swift
=> Deserialise and manage JSONRPC Responses in Relay

Sources/WalletConnect/Relay/Relay.swift, Sources/WalletConnect/Subscription.swift, Sources/WalletConnect/Subscription/Subscription.swift, Sources/WalletConnect/Subscription/SubscriptionParams.swift, Sources/WalletConnect/Types/Pairing/PairingProposal.swift, Sources/WalletConnect/Types/Pairing/PairingSettled.swift, Sources/WalletConnect/Types/Pairing/PairingSignal.swift, Tests/WalletConnectTests/Mocks/MockedRelay.swift, Tests/WalletConnectTests/SubscriptionTest.swift
=> #35   subscription

Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Engine/SequenceEngine.swift, Sources/WalletConnect/Types/Pairing/ClientSynchronisation/PairingApproveParams.swift, Sources/WalletConnect/Types/Pairing/PairingSettled.swift, Sources/WalletConnect/WalletConnectClient.swift
closes #41
Implements the (very) happy path for pairing settlement. Almost no errors are handled yet, and there are lots of room for refactors and improvements after the pairing validation.
=> #41 pairing engine

Sources/WalletConnect/Relay/Relay.swift, Sources/WalletConnect/Subscription/WCSubscribing.swift, Sources/WalletConnect/Subscription/WCSubscriptionPayload.swift, Tests/WalletConnectTests/Mocks/MockedRelay.swift, Tests/WalletConnectTests/SubscriptionTest.swift
=> #48 set observing for related payloads in wc subscriber

Sources/WalletConnect/Relay/Relay.swift, Tests/WalletConnectTests/RelayTests.swift, Tests/WalletConnectTests/TestsData/SerialiserTestData.swift
=> Fix: Handle of unencrypted subscription payload messages

Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/JSONRPC/JSONRPC.swift, Sources/WalletConnect/Relay/RelayJSONRPC.swift, Sources/WalletConnect/Subscription/WCSubscribing.swift, Sources/WalletConnect/Types/Pairing/ClientSynchronisation/PairingPayloadParams.swift, Sources/WalletConnect/Types/Pairing/PairingProposal.swift, Sources/WalletConnect/Types/Session/ClientSynchronisation/SessionProposeParams.swift, Sources/WalletConnect/Types/Session/SessionSettled.swift, Tests/WalletConnectTests/Mocks/MockedSubscriber.swift, Tests/WalletConnectTests/PairingEnginTests.swift, Tests/WalletConnectTests/SubscriptionTest.swift
=> Handle wc_pairing_payload in pairing engine

Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/Sequences/Session.swift, Sources/WalletConnect/Types/Session/SessionSettled.swift, Sources/WalletConnect/WalletConnectClient.swift
closes #53
Happy path for the session engine approval flow. As we progress, we can refactor the flow and fix some model issues.
=> #53 session engine

Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Example/ExampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/ExampleApp/AppDelegate.swift, Example/ExampleApp/Assets.xcassets/AccentColor.colorset/Contents.json, Example/ExampleApp/Assets.xcassets/AppIcon.appiconset/Contents.json, Example/ExampleApp/Assets.xcassets/Contents.json, Example/ExampleApp/Base.lproj/LaunchScreen.storyboard, Example/ExampleApp/Info.plist, Example/ExampleApp/ScannerViewController.swift, Example/ExampleApp/SceneDelegate.swift, Example/ExampleApp/ViewController.swift
closes #40
Adds an example sandbox App project that will interact with the SDK by scanning QR codes and starting pairings / sessions.
=> #40 example app

Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Sequences/Sequences.swift, Sources/WalletConnect/Subscription/WCSubscribing.swift, Sources/WalletConnect/Types/Pairing/ClientSynchronisation/PairingDeleteParams.swift, Tests/WalletConnectTests/SubscriptionTest.swift
=> #65 handle remove pairing

Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/Sequences/Sequences.swift, Sources/WalletConnect/Subscription/WCSubscribing.swift, Sources/WalletConnect/Types/Pairing/ClientSynchronisation/PairingDeleteParams.swift, Sources/WalletConnect/Types/PublicTypes/DisconnectParams.swift, Sources/WalletConnect/Types/Session/ClientSynchronisation/SessionDeleteParams.swift, Sources/WalletConnect/WalletConnectClient.swift, Tests/WalletConnectTests/Mocks/MockedRelay.swift, Tests/WalletConnectTests/Mocks/MockedSubscriber.swift, Tests/WalletConnectTests/PairingEnginTests.swift, Tests/WalletConnectTests/SessionEngineTests.swift, Tests/WalletConnectTests/SubscriptionTest.swift
=> #67 disconnect session

Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp/Proposer/ProposerView.swift, Example/ExampleApp/Proposer/ProposerViewController.swift
#closes 79
Add a QR code image view to proposer screen with a connect button action to mock the URI. Also adds a copy button to use later to copy the URI string directly.
=> #79 qr code proposer

Example/ExampleApp.xcodeproj/project.pbxproj, Example/ExampleApp/Proposer/ProposerViewController.swift, Example/ExampleApp/Responder/ResponderView.swift, Example/ExampleApp/Responder/ResponderViewController.swift, Sources/WalletConnect/Types/Common/AppMetadata.swift, Sources/WalletConnect/Types/Session/SessionProposal.swift, Sources/WalletConnect/Types/Session/SessionSettled.swift, Sources/WalletConnect/Types/Session/SessionSuccessResponse.swift
closes #81
Happy path on example app for session approval and settling, connecting 2 different clients.
Some public API of the SDK has been modified for convenience and will be reviewed later for improvements.
=> #81 uri string pairing

Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/WalletConnectClient.swift, Tests/IntegrationTests/ClientTest.swift
=> allow client to provide app state

Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/Sequences/UserDefaultsSequencesStore.swift, Sources/WalletConnect/Session.swift, Sources/WalletConnect/Types/Common/Controller.swift, Sources/WalletConnect/Types/Session/SessionProposal.swift, Sources/WalletConnect/Types/Session/SessionSettled.swift, Sources/WalletConnect/Types/Session/SessionSuccessResponse.swift, Sources/WalletConnect/WalletConnectClient.swift, Sources/WalletConnect/WalletConnectError.swift, Tests/IntegrationTests/ClientTest.swift
Implements update method allowed to call by controller and handles update request on non-controller client.
close #121
=> #121 update method

Sources/WalletConnect/WalletConnectClient.swift, Sources/WalletConnect/WalletConnectError.swift, Tests/IntegrationTests/ClientDelegate.swift, Tests/IntegrationTests/ClientTest.swift
=> Allow client to establish session on existing pairing

Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/Types/ClientSynchJSONRPC/ClientSynchJSONRPC.swift, Sources/WalletConnect/Types/ClientSynchJSONRPC/ClientSynchJSONRPC_Method.swift, Sources/WalletConnect/Types/ClientSynchJSONRPC/ClientSynchJSONRPC_Params.swift, Sources/WalletConnect/Types/Session/ClientSynchronisation/SessionNotificationParams.swift, Sources/WalletConnect/Types/Session/SessionProposal.swift, Sources/WalletConnect/Types/Session/SessionSettled.swift, Sources/WalletConnect/WalletConnectClient.swift, Sources/WalletConnect/WalletConnectError.swift, Tests/IntegrationTests/ClientDelegate.swift, Tests/IntegrationTests/ClientTest.swift
adds session notification method, fix session update to override existing state
close #122
=> #122 wc notification

Sources/WalletConnect/Extensions/String.swift, Sources/WalletConnect/Storage/KeyValueStorage.swift, Sources/WalletConnect/Storage/SequenceStore.swift, Tests/WalletConnectTests/Helpers/TimeTraveler.swift, Tests/WalletConnectTests/SequenceStoreTests.swift
closes #143
Adds a sequence store variation to handle sequence expiration on storage level. Will be integrated into the pairing and session engines to replace the current store.
=> #143 expirable storage

Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Types/Pairing/PairingSettled.swift, Sources/WalletConnect/Types/Pairing/PairingSuccessResponse.swift, Sources/WalletConnect/WalletConnectClient.swift, Tests/IntegrationTests/ClientDelegate.swift, Tests/IntegrationTests/ClientTest.swift
Responder updates `state.metadata` after pairing is established
close #145
=> #145 update metadata

Sources/WalletConnect/Session.swift
=> Make session proposals `Topic` as public

Sources/WalletConnect/Session.swift
Reverts WalletConnect-Labs/WalletConnectSwiftV2#149
=> Revert "Make session proposals `Topic` as public"

Example/ExampleApp/Proposer/ProposerViewController.swift, Example/ExampleApp/Responder/ResponderViewController.swift, Sources/WalletConnect/Engine/PairingEngine.swift, Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/Relay/WalletConnectRelay.swift, Sources/WalletConnect/Types/Pairing/PairingSettled.swift, Sources/WalletConnect/Types/Pairing/PairingSignal.swift, Sources/WalletConnect/Types/Session/ClientSynchronisation/SessionNotificationParams.swift, Sources/WalletConnect/WalletConnectClient.swift, Tests/IntegrationTests/ClientDelegate.swift
=> Fix example app build error

Example/ExampleApp/Proposer/ProposerViewController.swift, Example/ExampleApp/Responder/ResponderViewController.swift, Sources/WalletConnect/Session.swift, Sources/WalletConnect/Types/Session/SessionSuccessResponse.swift, Sources/WalletConnect/WalletConnectClient.swift
=> Not able to access to permissions in delegated method func didSettle(session: Session) #155

Sources/WalletConnect/Engine/SessionEngine.swift, Sources/WalletConnect/WalletConnectClient.swift, Tests/IntegrationTests/ClientTest.swift
=> handle session payload error responses

Example/ExampleApp/Proposer/ProposerViewController.swift, Example/ExampleApp/Responder/ResponderViewController.swift, README.md, Sources/Relayer/WakuNetworkRelay.swift, Sources/WalletConnect/Storage/SecureStorage.swift, Sources/WalletConnect/WalletConnectClient.swift, Tests/IntegrationTests/ClientTest.swift
I have also removed get and set apikey methods as they are not in use.
we can merge after receiving green light
=> rename apiKey to projectId
